package org.mytoypjt.exception;

public enum ErrorCode {

    // 로그인 관련
    ACCOUNT_IS_NOT_EXIST,

    // 프로필 관련
    PROFILE_IS_NOT_EXIST,

    // 아이디, 비밀번호 찾기 관련
    EMAIL_IS_NOT_EXIST,
    CERT_INPUT_IS_NOT_CORRECT,
    CERT_VALUE_IS_NULL,
    CERT_INPUT_IS_NULL,
    CERT_FAILURE,
    INPUT_PW_IS_NULL,
    INPUT_PW_CHECK_IS_NULL,

    // 회원가입 관련
    PASSWORD_CHECK_FAILURE,
    ID_IS_USING,
    ID_SEARCH_FAILURE,
    ACCOUNT_CREATION_FAILURE,
    PROFILE_CREATION_FAILURE,
    PROFILE_UPDATE_FAILURE,
    PROFILE_INPUT_GENDER_INCORRECT,
    PROFILE_INPUT_NICKNAME_INCORRECT,
    PROFILE_INPUT_NICKNAME_HAS_BLANK,
    PROFILE_INPUT_ITEM_HAS_NULL,
    MAIL_SEND_FAILURE,

    // 로그인 세션 관련
    ACCOUNT_IS_ALREADY_LOGIN

}
